# Generated by Django 3.1.4 on 2021-01-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_college_experience_resume_secondaryschool_skill_srsecondaryschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.customer'),
        ),
        migrations.AlterField(
            model_name='secondaryschool',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.customer'),
        ),
        migrations.AlterField(
            model_name='srsecondaryschool',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.customer'),
        ),
    ]
