# Generated by Django 3.1.4 on 2021-01-06 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0003_auto_20210101_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='collegeInfo',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='secondarySchoolInfo',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='srSecondarySchoolInfo',
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
